// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createBooking, getMemberBookings, cancelBooking, getAllBookings, getBookingById } from '@/services/bookingService';
import type { BookingDto, CreateBookingRequest } from '@/types/booking';

export function useCreateBooking(): { mutate: (vars: CreateBookingRequest) => void; mutateAsync: (vars: CreateBookingRequest) => Promise<BookingDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: CreateBookingRequest) => createBooking(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['booking'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useMemberBookings(): { data: BookingDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['booking', 'getMemberBookings'], queryFn: getMemberBookings });
  return { data, isLoading, isError, error };
}

export function useCancelBooking(): { mutate: (vars: number) => void; mutateAsync: (vars: number) => Promise<BookingDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (bookingId: number) => cancelBooking(bookingId),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['booking'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useBookings(): { data: BookingDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['booking', 'getAllBookings'], queryFn: getAllBookings });
  return { data, isLoading, isError, error };
}

export function useBookingById(bookingId: number): { data: BookingDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['booking', 'getBookingById', bookingId], queryFn: () => getBookingById(bookingId) });
  return { data, isLoading, isError, error };
}
