// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createBooking, getMemberBookings, getBookingById, cancelBooking, getAllBookings, adminGetBookingById, adminCancelBooking } from '@/services/bookingService';
import type { BookingDto, CreateBookingRequest } from '@/types/booking';

export function useCreateBooking(): { mutate: (vars: CreateBookingRequest) => void; mutateAsync: (vars: CreateBookingRequest) => Promise<BookingDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: CreateBookingRequest) => createBooking(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['booking'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useMemberBookings(): { data: BookingDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['booking', 'getMemberBookings'], queryFn: getMemberBookings });
  return { data, isLoading, isError, error };
}

export function useBookingById(id: string): { data: BookingDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['booking', 'getBookingById', id], queryFn: () => getBookingById(id) });
  return { data, isLoading, isError, error };
}

export function useCancelBooking(): { mutate: (vars: string) => void; mutateAsync: (vars: string) => Promise<BookingDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: string) => cancelBooking(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['booking'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useBookings(): { data: BookingDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['booking', 'getAllBookings'], queryFn: getAllBookings });
  return { data, isLoading, isError, error };
}

export function useAdminGetBookingById(id: string): { data: BookingDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['booking', 'adminGetBookingById', id], queryFn: () => adminGetBookingById(id) });
  return { data, isLoading, isError, error };
}

export function useAdminCancelBooking(): { mutate: (vars: string) => void; mutateAsync: (vars: string) => Promise<BookingDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: string) => adminCancelBooking(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['booking'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
