// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createEnquiry, getAllEnquiries, getEnquiryById } from '@/services/enquiryService';
import type { EnquiryDto } from '@/types/enquiry';

export function useCreateEnquiry(): { mutate: (vars: EnquiryDto) => void; mutateAsync: (vars: EnquiryDto) => Promise<EnquiryDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: EnquiryDto) => createEnquiry(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['enquiry'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useEnquiries(): { data: EnquiryDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['enquiry', 'getAllEnquiries'], queryFn: getAllEnquiries });
  return { data, isLoading, isError, error };
}

export function useEnquiryById(id: string): { data: EnquiryDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['enquiry', 'getEnquiryById', id], queryFn: () => getEnquiryById(id) });
  return { data, isLoading, isError, error };
}
