// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQueryClient } from '@tanstack/react-query';
import { deleteFitnessClass } from '@/services/fitness-classService';

export function useDeleteFitnessClass(): { mutate: (vars: number) => void; mutateAsync: (vars: number) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteFitnessClass(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['fitness-class'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
