// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getAllAvailableFitnessClasses, getFitnessClassById, getAllFitnessClasses, adminGetFitnessClassById, createFitnessClass, updateFitnessClass } from '@/services/fitnessClassService';
import type { FitnessClassDto } from '@/types/fitnessClass';

export function useAvailableFitnessClasses(): { data: FitnessClassDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['fitnessClass', 'getAllAvailableFitnessClasses'], queryFn: getAllAvailableFitnessClasses });
  return { data, isLoading, isError, error };
}

export function useFitnessClassById(id: number): { data: FitnessClassDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['fitnessClass', 'getFitnessClassById', id], queryFn: () => getFitnessClassById(id) });
  return { data, isLoading, isError, error };
}

export function useFitnessClasses(): { data: FitnessClassDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['fitnessClass', 'getAllFitnessClasses'], queryFn: getAllFitnessClasses });
  return { data, isLoading, isError, error };
}

export function useAdminGetFitnessClassById(id: number): { data: FitnessClassDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['fitnessClass', 'adminGetFitnessClassById', id], queryFn: () => adminGetFitnessClassById(id) });
  return { data, isLoading, isError, error };
}

export function useCreateFitnessClass(): { mutate: (vars: FitnessClassDto) => void; mutateAsync: (vars: FitnessClassDto) => Promise<FitnessClassDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: FitnessClassDto) => createFitnessClass(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['fitnessClass'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateFitnessClass(): { mutate: (vars: { id: number; request: FitnessClassDto }) => void; mutateAsync: (vars: { id: number; request: FitnessClassDto }) => Promise<FitnessClassDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: FitnessClassDto }) => updateFitnessClass(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['fitnessClass'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
