// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getAllFitnessClasses, getFitnessClassById, createFitnessClass, adminGetAllFitnessClasses, adminGetFitnessClassById, updateFitnessClass, deleteFitnessClass } from '@/services/fitnessClassService';
import type { FitnessClassDto } from '@/types/fitnessClass';

export function useFitnessClasses(): { data: FitnessClassDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['fitnessClass', 'getAllFitnessClasses'], queryFn: getAllFitnessClasses });
  return { data, isLoading, isError, error };
}

export function useFitnessClassById(id: string): { data: FitnessClassDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['fitnessClass', 'getFitnessClassById', id], queryFn: () => getFitnessClassById(id) });
  return { data, isLoading, isError, error };
}

export function useCreateFitnessClass(): { mutate: (vars: FitnessClassDto) => void; mutateAsync: (vars: FitnessClassDto) => Promise<FitnessClassDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: FitnessClassDto) => createFitnessClass(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['fitnessClass'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useAdminGetAllFitnessClasses(): { data: FitnessClassDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['fitnessClass', 'adminGetAllFitnessClasses'], queryFn: adminGetAllFitnessClasses });
  return { data, isLoading, isError, error };
}

export function useAdminGetFitnessClassById(id: string): { data: FitnessClassDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['fitnessClass', 'adminGetFitnessClassById', id], queryFn: () => adminGetFitnessClassById(id) });
  return { data, isLoading, isError, error };
}

export function useUpdateFitnessClass(): { mutate: (vars: { id: string; request: FitnessClassDto }) => void; mutateAsync: (vars: { id: string; request: FitnessClassDto }) => Promise<FitnessClassDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: string; request: FitnessClassDto }) => updateFitnessClass(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['fitnessClass'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteFitnessClass(): { mutate: (vars: string) => void; mutateAsync: (vars: string) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: string) => deleteFitnessClass(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['fitnessClass'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
