// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createInquiry, getAllInquiries, getInquiryById, deleteInquiry } from '@/services/inquiryService';
import type { CreateInquiryRequest, InquiryDto } from '@/types/inquiry';

export function useCreateInquiry(): { mutate: (vars: CreateInquiryRequest) => void; mutateAsync: (vars: CreateInquiryRequest) => Promise<InquiryDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: CreateInquiryRequest) => createInquiry(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['inquiry'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useInquiries(): { data: InquiryDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['inquiry', 'getAllInquiries'], queryFn: getAllInquiries });
  return { data, isLoading, isError, error };
}

export function useInquiryById(id: number): { data: InquiryDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['inquiry', 'getInquiryById', id], queryFn: () => getInquiryById(id) });
  return { data, isLoading, isError, error };
}

export function useDeleteInquiry(): { mutate: (vars: number) => void; mutateAsync: (vars: number) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteInquiry(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['inquiry'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
