// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getAllMembershipPlans, getMembershipPlanById, createSubscription, getMemberSubscriptions, verifySubscriptionPayment, createMembershipPlan, adminGetAllMembershipPlans, adminGetMembershipPlanById, updateMembershipPlan, deleteMembershipPlan } from '@/services/membershipService';
import type { MemberSubscription, MembershipPlanDto } from '@/types/membership';
import type { PaymentOrderResponse } from '@/types/payment';
import type { VerifyPaymentRequest } from '@/types/verify';

export function useMembershipPlans(): { data: MembershipPlanDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['membership', 'getAllMembershipPlans'], queryFn: getAllMembershipPlans });
  return { data, isLoading, isError, error };
}

export function useMembershipPlanById(id: number): { data: MembershipPlanDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['membership', 'getMembershipPlanById', id], queryFn: () => getMembershipPlanById(id) });
  return { data, isLoading, isError, error };
}

export function useCreateSubscription(): { mutate: (vars: unknown) => void; mutateAsync: (vars: unknown) => Promise<PaymentOrderResponse>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: unknown) => createSubscription(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['membership'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useMemberSubscriptions(): { data: MemberSubscription[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['membership', 'getMemberSubscriptions'], queryFn: getMemberSubscriptions });
  return { data, isLoading, isError, error };
}

export function useVerifySubscriptionPayment(): { mutate: (vars: VerifyPaymentRequest) => void; mutateAsync: (vars: VerifyPaymentRequest) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: VerifyPaymentRequest) => verifySubscriptionPayment(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['membership'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useCreateMembershipPlan(): { mutate: (vars: MembershipPlanDto) => void; mutateAsync: (vars: MembershipPlanDto) => Promise<MembershipPlanDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: MembershipPlanDto) => createMembershipPlan(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['membership'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useAdminGetAllMembershipPlans(): { data: MembershipPlanDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['membership', 'adminGetAllMembershipPlans'], queryFn: adminGetAllMembershipPlans });
  return { data, isLoading, isError, error };
}

export function useAdminGetMembershipPlanById(id: number): { data: MembershipPlanDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['membership', 'adminGetMembershipPlanById', id], queryFn: () => adminGetMembershipPlanById(id) });
  return { data, isLoading, isError, error };
}

export function useUpdateMembershipPlan(): { mutate: (vars: { id: number; request: MembershipPlanDto }) => void; mutateAsync: (vars: { id: number; request: MembershipPlanDto }) => Promise<MembershipPlanDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: MembershipPlanDto }) => updateMembershipPlan(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['membership'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteMembershipPlan(): { mutate: (vars: number) => void; mutateAsync: (vars: number) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteMembershipPlan(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['membership'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
