// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getActiveMembershipPlans, getMembershipPlanById, getMemberSubscriptions, getMemberSubscriptionById, createMemberSubscription, cancelMemberSubscription, getAllMembershipPlans, adminGetMembershipPlanById, createMembershipPlan, updateMembershipPlan, deleteMembershipPlan } from '@/services/membershipService';
import type { MemberSubscriptionDto, MembershipPlanDto } from '@/types/membership';

export function useActiveMembershipPlans(): { data: MembershipPlanDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['membership', 'getActiveMembershipPlans'], queryFn: getActiveMembershipPlans });
  return { data, isLoading, isError, error };
}

export function useMembershipPlanById(id: number): { data: MembershipPlanDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['membership', 'getMembershipPlanById', id], queryFn: () => getMembershipPlanById(id) });
  return { data, isLoading, isError, error };
}

export function useMemberSubscriptions(): { data: MemberSubscriptionDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['membership', 'getMemberSubscriptions'], queryFn: getMemberSubscriptions });
  return { data, isLoading, isError, error };
}

export function useMemberSubscriptionById(id: number): { data: MemberSubscriptionDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['membership', 'getMemberSubscriptionById', id], queryFn: () => getMemberSubscriptionById(id) });
  return { data, isLoading, isError, error };
}

export function useCreateMemberSubscription(): { mutate: (vars: unknown) => void; mutateAsync: (vars: unknown) => Promise<MemberSubscriptionDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: unknown) => createMemberSubscription(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['membership'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useCancelMemberSubscription(): { mutate: (vars: number) => void; mutateAsync: (vars: number) => Promise<MemberSubscriptionDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => cancelMemberSubscription(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['membership'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useMembershipPlans(): { data: MembershipPlanDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['membership', 'getAllMembershipPlans'], queryFn: getAllMembershipPlans });
  return { data, isLoading, isError, error };
}

export function useAdminGetMembershipPlanById(id: number): { data: MembershipPlanDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['membership', 'adminGetMembershipPlanById', id], queryFn: () => adminGetMembershipPlanById(id) });
  return { data, isLoading, isError, error };
}

export function useCreateMembershipPlan(): { mutate: (vars: MembershipPlanDto) => void; mutateAsync: (vars: MembershipPlanDto) => Promise<MembershipPlanDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: MembershipPlanDto) => createMembershipPlan(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['membership'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateMembershipPlan(): { mutate: (vars: { id: number; request: MembershipPlanDto }) => void; mutateAsync: (vars: { id: number; request: MembershipPlanDto }) => Promise<MembershipPlanDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: MembershipPlanDto }) => updateMembershipPlan(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['membership'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteMembershipPlan(): { mutate: (vars: number) => void; mutateAsync: (vars: number) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteMembershipPlan(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['membership'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
