// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useQuery } from '@tanstack/react-query';
import { getAllGoogleReviews } from '@/services/reviewService';
import type { GoogleReviewDto } from '@/types/review';

export function useGoogleReviews(): { data: GoogleReviewDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['review', 'getAllGoogleReviews'], queryFn: getAllGoogleReviews });
  return { data, isLoading, isError, error };
}
