// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getApprovedReviews, getAllReviews, getReviewById, createReview, updateReview, deleteReview, approveReview } from '@/services/reviewService';
import type { ReviewDto } from '@/types/review';

export function useApprovedReviews(): { data: ReviewDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['review', 'getApprovedReviews'], queryFn: getApprovedReviews });
  return { data, isLoading, isError, error };
}

export function useReviews(): { data: ReviewDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['review', 'getAllReviews'], queryFn: getAllReviews });
  return { data, isLoading, isError, error };
}

export function useReviewById(id: number): { data: ReviewDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['review', 'getReviewById', id], queryFn: () => getReviewById(id) });
  return { data, isLoading, isError, error };
}

export function useCreateReview(): { mutate: (vars: ReviewDto) => void; mutateAsync: (vars: ReviewDto) => Promise<ReviewDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: ReviewDto) => createReview(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['review'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateReview(): { mutate: (vars: { id: number; request: ReviewDto }) => void; mutateAsync: (vars: { id: number; request: ReviewDto }) => Promise<ReviewDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: ReviewDto }) => updateReview(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['review'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteReview(): { mutate: (vars: number) => void; mutateAsync: (vars: number) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteReview(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['review'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useApproveReview(): { mutate: (vars: number) => void; mutateAsync: (vars: number) => Promise<ReviewDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => approveReview(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['review'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
