// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getAllTrainers, getTrainerById, adminGetAllTrainers, adminGetTrainerById, createTrainer, updateTrainer, deleteTrainer } from '@/services/trainerService';
import type { TrainerDto } from '@/types/trainer';

export function useTrainers(): { data: TrainerDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['trainer', 'getAllTrainers'], queryFn: getAllTrainers });
  return { data, isLoading, isError, error };
}

export function useTrainerById(id: number): { data: TrainerDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['trainer', 'getTrainerById', id], queryFn: () => getTrainerById(id) });
  return { data, isLoading, isError, error };
}

export function useAdminGetAllTrainers(): { data: TrainerDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['trainer', 'adminGetAllTrainers'], queryFn: adminGetAllTrainers });
  return { data, isLoading, isError, error };
}

export function useAdminGetTrainerById(id: number): { data: TrainerDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['trainer', 'adminGetTrainerById', id], queryFn: () => adminGetTrainerById(id) });
  return { data, isLoading, isError, error };
}

export function useCreateTrainer(): { mutate: (vars: TrainerDto) => void; mutateAsync: (vars: TrainerDto) => Promise<TrainerDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: TrainerDto) => createTrainer(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['trainer'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateTrainer(): { mutate: (vars: { id: number; request: TrainerDto }) => void; mutateAsync: (vars: { id: number; request: TrainerDto }) => Promise<TrainerDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: TrainerDto }) => updateTrainer(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['trainer'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteTrainer(): { mutate: (vars: number) => void; mutateAsync: (vars: number) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteTrainer(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['trainer'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
