package com.absfitness.service;

import com.absfitness.dto.TrainerDto;
import com.absfitness.exception.ResourceNotFoundException;
import com.absfitness.model.Trainer;
import com.absfitness.repository.TrainerRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class TrainerService {

    private final TrainerRepository trainerRepository;

    public TrainerService(TrainerRepository trainerRepository) {
        this.trainerRepository = trainerRepository;
    }

    public TrainerDto createTrainer(TrainerDto trainerDto) {
        Trainer trainer = toEntity(trainerDto);
        Trainer savedTrainer = trainerRepository.save(trainer);
        return toDto(savedTrainer);
    }

    public List<TrainerDto> getAllTrainers() {
        return trainerRepository.findAll().stream()
                .map(this::toDto)
                .collect(Collectors.toList());
    }

    public TrainerDto getTrainerById(UUID id) {
        Trainer trainer = trainerRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Trainer not found with ID: " + id));
        return toDto(trainer);
    }

    public TrainerDto updateTrainer(UUID id, TrainerDto trainerDto) {
        if (!trainerRepository.existsById(id)) {
            throw new ResourceNotFoundException("Trainer not found with ID: " + id);
        }
        Trainer trainer = toEntity(trainerDto);
        trainer.setId(id); // Ensure the ID is set for update
        Trainer updatedTrainer = trainerRepository.save(trainer);
        return toDto(updatedTrainer);
    }

    public void deleteTrainer(UUID id) {
        if (!trainerRepository.existsById(id)) {
            throw new ResourceNotFoundException("Trainer not found with ID: " + id);
        }
        trainerRepository.deleteById(id);
    }

    private TrainerDto toDto(Trainer trainer) {
        return TrainerDto.builder()
                .id(trainer.getId() != null ? trainer.getId().getMostSignificantBits() : null) // Assuming Long id in DTO is for display/convenience
                .name(trainer.getName())
                .specialties(trainer.getSpecialties() != null ? String.join(", ", trainer.getSpecialties()) : null)
                .bio(trainer.getBio())
                .photoUrl(trainer.getPhotoUrl())
                .build();
    }

    private Trainer toEntity(TrainerDto trainerDto) {
        Trainer trainer = new Trainer();
        // ID is typically generated by the DB for new entities, or set for updates
        // trainer.setId(trainerDto.getId() != null ? UUID.fromString(String.valueOf(trainerDto.getId())) : null); // UUID conversion for ID is complex here, assuming new entity or ID set by update method
        trainer.setName(trainerDto.getName());
        trainer.setSpecialties(trainerDto.getSpecialties() != null ? List.of(trainerDto.getSpecialties().split(", ")) : null);
        trainer.setBio(trainerDto.getBio());
        trainer.setPhotoUrl(trainerDto.getPhotoUrl());
        return trainer;
    }
}